name: clipora
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

isar_version: &isar_version 3.1.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  dio: ^5.6.0
  get: ^4.7.2
  get_storage: ^2.1.1                             # 轻量级键值对存储库
  go_router: ^15.1.2
  intl: ^0.20.2
  logger: ^2.4.0
  shared_preferences: ^2.3.1
  bot_toast: ^4.1.3
  screenshot: ^3.0.0                               # 将widget内容保存为图片
  path_provider: ^2.1.5                            # 获取文件路径
  permission_handler: ^12.0.0+1                    # 权限处理
  image: ^4.5.4                                    # 图片处理和拼接
#  receive_sharing_intent: ^1.8.1                   # 接收分享内容
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent.git
      ref: master
  fluwx: ^5.5.5                                    # 微信集成库
  url_launcher: ^6.3.1                             # 打开外部链接
  device_info_plus: 11.3.0                        # 获取设备信息

  animated_segmented_tab_control: ^2.0.0           # 切换tab
  markdown_widget: ^2.3.2+8
  flutter_markdown_selectionarea: ^0.6.17+1        # 支持 SelectionArea 的 MarkdownWidget
  page_flip_builder: ^0.1.4
  modal_bottom_sheet: ^3.0.0
  # app_links: ^6.3.2                              # 处理URL Scheme和Universal Links
  # device_info_plus: ^9.1.2                       # 设备信息
  # isar: ^3.1.0+1                                 # NoSQL本地数据库
  # isar_flutter_libs: ^3.1.0+1                    # Isar 原生库文件
  uuid: ^4.5.1
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  # isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.14.4
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/

flutter:

  uses-material-design: true
  assets:
      - assets/
      - assets/js/ # 确保这行或 assets/js/html2canvas.min.js 被添加


fluwx:
  app_id: wx629011ac595bee08
  # only debug in debug mode
  debug_logging: true
  android:
  #      interrupt_wx_request: true # default is true
  #      flutter_activity: MainActivity #Default to launch app's launcher
  ios:
    universal_link: https://flint-tools.guanshangyun.com
    #    scene_delegate: true #default false
    # payment is enabled by default
    no_pay: false

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/logo.png"
  image_path_android: "assets/logo.png"
